[package]
name = "weewx-cli"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
axum = "0.7"
tokio = { version = "1.35", features = ["full"] }
tracing = "0.1"
weewx-obs = { path = "../weewx-obs" }
weewx-config = { path = "../weewx-config" }

