[station]
id = "home"
timezone = "America/Chicago"

[sinks.http]
bind = "0.0.0.0:8080"

[sinks.fs]
# Optional: when set, write JSONL to this directory
# dir = "/var/lib/weewx"

[sinks.sqlite]
# Optional: write packets to SQLite database file (feature: weewx-sinks/sqlite)
# path = "/var/lib/weewx/weewx.db"

[sinks.postgres]
# Optional: write packets to Postgres (feature: weewx-sinks/postgres)
# url = "postgres://user:pass@localhost:5432/weewx"

[sinks.influx]
# Optional: write packets to InfluxDB v2 (feature: weewx-sinks/influx)
# url = "http://localhost:8086"
# org = "my-org"
# bucket = "weewx"
# token = "INFLUXDB_TOKEN"

[ingest.interceptor]
# INTERCEPTOR UDP bind address (useful for devices that broadcast UDP; GW1100 does not)
bind = "0.0.0.0:9999"

# Ecowitt HTTP ingest: GW1100 Customized Server should point to http://<host>:8080/ingest/ecowitt
# No additional config is required beyond [sinks.http.bind].
