[package]
name = "weewx-obs"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"] }

